import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.wrapper}>
          <div className={styles["scroll-container"]}>
            <div className={styles["scroll-area"]}>1</div>
            <div className={styles["scroll-area"]}>2</div>
            <div className={styles["scroll-area"]}>3</div>
            <div className={styles["scroll-area"]}>4</div>
          </div>
          <div className={styles["scroll-container"]}>
            <div className={styles["scroll-area"]}>1</div>
            <div className={styles["scroll-area"]}>2</div>
            <div className={styles["scroll-area"]}>3</div>
            <div className={styles["scroll-area"]}>4</div>
          </div>
        </div>
      </main>
    </>
  );
}
